import streamlit as st

from src.db import fetch_df, execute, now
from src.llm import generate_prd, generate_user_stories, generate_executive_summary, generate_quick_prd_from_feedback
from utils.helpers import (
    ws_id, fetch_feedback, fetch_features, fetch_documents,
    fetch_prioritized_backlog, ensure_rice_score, save_rice_score, priority_bucket,
)


def _inject_css():
    st.markdown("""
        <style>
        .report-card {
            background: var(--pm-bg);
            border: 1px solid var(--pm-border);
            border-radius: 14px;
            padding: 16px 18px;
            margin-bottom: 12px;
            box-shadow: var(--pm-shadow);
        }
        .report-title { font-size: 15px; font-weight: 700; color: var(--pm-navy); margin-bottom: 2px; }
        .report-desc { font-size: 13px; color: var(--pm-text-muted); margin-bottom: 6px; }
        .report-meta { font-size: 12px; color: var(--pm-text-muted); }
        .priority-badge {
            font-size: 11px; font-weight: 600; padding: 3px 10px; border-radius: 20px;
        }
        .priority-high { background: var(--pm-red-bg); color: var(--pm-red); }
        .priority-medium { background: var(--pm-amber-bg); color: var(--pm-amber); }
        .priority-low { background: var(--pm-green-bg); color: var(--pm-green); }
        </style>
    """, unsafe_allow_html=True)


def _priority_class(priority):
    return {"High": "priority-high", "Medium": "priority-medium", "Low": "priority-low"}.get(priority, "priority-medium")


def show_reports():
    _inject_css()

    feedback = fetch_feedback()
    features = fetch_features()
    docs = fetch_documents()

    header_col, btn_col = st.columns([5, 1.4])
    with header_col:
        st.markdown("### 📊 Reports")
        st.caption("AI-generated insights and documents, generated by the real Gemini/CrewAI backend "
                    "(falls back to an offline template if no GEMINI_API_KEY is configured).")
    with btn_col:
        st.write("")
        gen_clicked = st.button("+ Generate New PRD", type="primary", use_container_width=True,
                                 disabled=features.empty)
        if features.empty:
            st.caption("No feature requests in the database yet.")

    if gen_clicked and not features.empty:
        # Generate for the highest-voted feature request that doesn't have a PRD yet, else the top one.
        docs_titles = set(docs["title"]) if not docs.empty else set()
        candidates = features[~features["title"].isin(docs_titles)]
        target = candidates.iloc[0] if not candidates.empty else features.iloc[0]

        theme_feedback = fetch_df(
            "SELECT text FROM feedback WHERE workspace_id = ? AND theme = ?", (ws_id(), target["theme"])
        )
        samples = theme_feedback["text"].tolist()

        with st.spinner(f"Drafting PRD for '{target['title']}'..."):
            prd = generate_prd(target["title"], target["description"] or "", target["theme"] or "General", samples)
        execute(
            "INSERT INTO documents (workspace_id, doc_type, title, content, created_at) VALUES (?,?,?,?,?)",
            (ws_id(), "PRD", target["title"], prd, now()),
        )
        st.success(f"✅ New PRD generated for '{target['title']}'!")
        st.rerun()

    st.write("")

    tab_prd, tab_priorities, tab_summary, tab_insights = st.tabs(
        ["PRD Documents", "Feature Priorities", "Executive Summary", "Feedback Insights"]
    )

    # -----------------------------
    # PRD Documents (real: src/db `documents` table, generated via src/llm)
    # -----------------------------
    with tab_prd:
        # -----------------------------
        # Quick PRD from raw feedback (ported from Team3_AICopilot_backend's
        # Feedback -> Feature -> Priority -> PRD agent chain). Doesn't need
        # feedback to already be ingested/classified — paste anything.
        # -----------------------------
        with st.expander("⚡ Quick PRD from raw feedback (no ingestion needed)"):
            st.caption(
                "Paste raw customer feedback, support tickets, or a feature ask. This runs it through "
                "a 4-agent chain (Feedback → Feature → Priority → PRD) and drafts a mini-PRD directly, "
                "without needing the text to already be in the database."
            )
            quick_text = st.text_area(
                "Raw feedback / support tickets / feature ask",
                height=140,
                placeholder="e.g. Users complaining that export takes 3 minutes and times out on 5000 rows. "
                             "Requesting async email export.",
                key="quick_prd_input",
            )
            if st.button("🚀 Generate Mini-PRD", key="quick_prd_button", disabled=not quick_text.strip()):
                with st.spinner("Running Feedback → Feature → Priority → PRD agents..."):
                    stages = generate_quick_prd_from_feedback(quick_text.strip())
                st.session_state["quick_prd_stages"] = stages

            stages = st.session_state.get("quick_prd_stages")
            if stages:
                prd_stage = next((s for s in stages if s["stage"] == "PRD"), stages[-1])
                if len(stages) > 1:
                    stage_tabs = st.tabs([s["stage"] for s in stages])
                    for stab, s in zip(stage_tabs, stages):
                        with stab:
                            st.markdown(s["output"])
                else:
                    st.markdown(prd_stage["output"])

                title_guess = quick_text.strip().splitlines()[0][:60] if quick_text.strip() else "Quick PRD"
                if st.button("💾 Save PRD to documents", key="save_quick_prd"):
                    execute(
                        "INSERT INTO documents (workspace_id, doc_type, title, content, created_at) VALUES (?,?,?,?,?)",
                        (ws_id(), "PRD", title_guess, prd_stage["output"], now()),
                    )
                    st.session_state.pop("quick_prd_stages", None)
                    st.success("✅ Saved to PRD Documents below.")
                    st.rerun()

        st.write("")

        if docs.empty:
            st.info("No PRDs generated yet. Click **+ Generate New PRD** above once you have feature requests.")
        for i, doc in docs.reset_index(drop=True).iterrows():
            # derive a priority badge from RICE (if the doc's title matches a scored feature)
            match = features[features["title"] == doc["title"]]
            rice = None
            if not match.empty:
                scored = ensure_rice_score(match.iloc[0])
                rice = scored.get("rice_score")
            badge = priority_bucket(rice)

            st.markdown(f"""
                <div class="report-card">
                    <div style="display:flex; justify-content:space-between; align-items:flex-start;">
                        <div>
                            <div class="report-title">📄 {doc['title']} <span style="font-weight:400;color:var(--pm-text-muted);">({doc['doc_type']})</span></div>
                            <div class="report-meta">Generated on {str(doc['created_at'])[:10]}</div>
                        </div>
                        <span class="priority-badge {_priority_class(badge)}">{badge} Priority</span>
                    </div>
                </div>
            """, unsafe_allow_html=True)

            v_col, d_col, _ = st.columns([1, 1, 5])
            with v_col:
                if st.button("👁 View", key=f"view_prd_{doc['id']}"):
                    st.session_state.active_prd_view = (
                        None if st.session_state.get("active_prd_view") == doc["id"] else doc["id"]
                    )
            with d_col:
                st.download_button(
                    "⬇ Download", doc["content"],
                    file_name=f"{doc['doc_type']}_{doc['title'][:30]}.md", mime="text/markdown",
                    key=f"download_prd_{doc['id']}",
                )

            if st.session_state.get("active_prd_view") == doc["id"]:
                with st.container(border=True):
                    st.markdown(doc["content"])

        st.write("")
        st.caption("Prefer user stories instead of a full PRD? Generate them for a specific feature below.")
        if not features.empty:
            us_feature = st.selectbox("Feature", features["title"].tolist(), key="us_feature_select")
            if st.button("Generate user stories", key="gen_user_stories"):
                row = features[features["title"] == us_feature].iloc[0]
                with st.spinner("Writing user stories..."):
                    stories = generate_user_stories(row["title"], row["description"] or "")
                execute(
                    "INSERT INTO documents (workspace_id, doc_type, title, content, created_at) VALUES (?,?,?,?,?)",
                    (ws_id(), "User Stories", row["title"], stories, now()),
                )
                st.rerun()

    # -----------------------------
    # Feature Priorities (real: RICE scoring, AI-suggested impact via src/llm)
    # -----------------------------
    with tab_priorities:
        st.caption("Ranked by RICE score (Reach × Impact × Confidence ÷ Effort). Newly seen features get a "
                   "sensible default score automatically; use **AI-suggest impact** to refine it.")
        if features.empty:
            st.info("No feature requests tracked yet — upload & analyze feedback first.")
        else:
            backlog = fetch_prioritized_backlog().sort_values("rice_score", ascending=False, na_position="last")
            max_votes = max(int(features["votes"].max()), 1)

            for _, row in backlog.iterrows():
                feature_row = features[features["id"] == row["feature_id"]].iloc[0]
                scored = ensure_rice_score(feature_row) if row["rice_score"] != row["rice_score"] or row["rice_score"] is None else row

                with st.container(border=True):
                    c1, c2, c3 = st.columns([3, 2, 1.3])
                    c1.write(f"**{row['title']}**")
                    c1.caption(f"Theme: {row['theme']}")
                    c2.progress(min(row["votes"] / max_votes, 1.0), text=f"{row['votes']} votes")
                    bucket = priority_bucket(scored.get("rice_score", row["rice_score"]))
                    c3.markdown(f'<span class="priority-badge {_priority_class(bucket)}">{bucket}</span>',
                                unsafe_allow_html=True)

                    with st.expander("Adjust RICE score"):
                        rc1, rc2, rc3, rc4, rc5 = st.columns([1, 1, 1, 1, 1.3])
                        reach = rc1.number_input("Reach", min_value=0, value=int(scored.get("reach", row["votes"] * 10)),
                                                  key=f"reach_{row['feature_id']}")
                        if rc2.button("AI-suggest impact", key=f"ai_{row['feature_id']}"):
                            from src.llm import suggest_impact_score
                            suggestion = suggest_impact_score(row["title"], feature_row["description"] or "", int(row["votes"]))
                            st.session_state[f"impact_default_{row['feature_id']}"] = suggestion
                        default_impact = st.session_state.get(
                            f"impact_default_{row['feature_id']}", int(scored.get("impact", 3))
                        )
                        impact = rc2.slider("Impact", 1, 5, default_impact, key=f"impact_{row['feature_id']}")
                        confidence = rc3.slider("Confidence %", 0, 100, int(scored.get("confidence", 80)),
                                                 key=f"conf_{row['feature_id']}")
                        effort = rc4.number_input("Effort (person-months)", min_value=0.5,
                                                   value=float(scored.get("effort", 2.0)), step=0.5,
                                                   key=f"effort_{row['feature_id']}")
                        live_rice = (reach * impact * (confidence / 100)) / max(effort, 0.1)
                        rc5.metric("RICE score", f"{live_rice:,.1f}")
                        if st.button("Save score", key=f"save_{row['feature_id']}"):
                            save_rice_score(int(row["feature_id"]), reach, impact, confidence, effort)
                            st.success("Saved.")
                            st.rerun()

            st.write("")
            st.subheader("Prioritized backlog")
            display_backlog = fetch_prioritized_backlog().sort_values("rice_score", ascending=False, na_position="last")
            st.dataframe(display_backlog, use_container_width=True, hide_index=True)
            if display_backlog["rice_score"].notna().any():
                st.bar_chart(display_backlog.dropna(subset=["rice_score"]).set_index("title")["rice_score"])

    # -----------------------------
    # Executive Summary (real: computed metrics + src/llm.generate_executive_summary)
    # -----------------------------
    with tab_summary:
        total_fb = len(feedback)
        high_priority = 0
        avg_sentiment = None
        if not feedback.empty and feedback["sentiment_score"].notna().any():
            avg_sentiment = round(float(feedback["sentiment_score"].dropna().mean()), 2)
        if not features.empty:
            backlog = fetch_prioritized_backlog()
            high_priority = int((backlog["rice_score"].apply(priority_bucket) == "High").sum())

        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Total Feedback", f"{total_fb:,}")
        c2.metric("High Priority Features", str(high_priority))
        c3.metric("Avg. Sentiment Score", f"{avg_sentiment}" if avg_sentiment is not None else "—")
        c4.metric("PRDs Generated", str(len(docs[docs["doc_type"] == "PRD"])) if not docs.empty else "0")

        st.write("")
        if st.button("✨ Generate AI executive summary", type="primary"):
            context_parts = []
            if not feedback.empty:
                context_parts.append(
                    f"Total feedback items: {total_fb}. "
                    f"Sentiment split: {feedback['sentiment'].value_counts().to_dict() if feedback['sentiment'].notna().any() else 'not classified yet'}. "
                    f"Top themes: {feedback['theme'].value_counts().head(5).to_dict() if feedback['theme'].notna().any() else 'not classified yet'}."
                )
            if not features.empty:
                context_parts.append(
                    f"Feature requests tracked: {len(features)}. "
                    f"Status breakdown: {features['status'].value_counts().to_dict()}."
                )
            backlog = fetch_prioritized_backlog()
            if not backlog.empty and backlog["rice_score"].notna().any():
                top5 = backlog.sort_values("rice_score", ascending=False).head(5)
                context_parts.append("Top prioritized features by RICE score: " + ", ".join(
                    f"{r.title} ({r.rice_score:.1f})" for r in top5.itertuples() if r.rice_score
                ))
            context = "\n".join(context_parts) if context_parts else "No data has been ingested into this workspace yet."

            with st.spinner("Writing executive summary..."):
                summary = generate_executive_summary(context)
            st.session_state["exec_summary"] = summary

        if st.session_state.get("exec_summary"):
            with st.container(border=True):
                st.markdown(st.session_state["exec_summary"])
            st.download_button("Download summary", st.session_state["exec_summary"],
                                file_name="executive_summary.md", mime="text/markdown")

    # -----------------------------
    # Feedback Insights (real: from the `feedback` table)
    # -----------------------------
    with tab_insights:
        with st.container(border=True):
            st.subheader("📌 Top Issues")
            if not feedback.empty and feedback["theme"].notna().any():
                neg = feedback[feedback["sentiment"] == "Negative"]
                for theme, count in neg["theme"].value_counts().head(5).items():
                    st.write(f"• {theme} — {count} mentions")
            else:
                st.caption("No classified feedback in the database yet.")

        with st.container(border=True):
            st.subheader("💡 Top Requested Features")
            if not features.empty:
                for _, row in features.head(5).iterrows():
                    st.write(f"• {row['title']} — {row['votes']} requests")
            else:
                st.caption("No feature requests tracked yet.")

        with st.container(border=True):
            st.subheader("😊 Sentiment Breakdown")
            if not feedback.empty and feedback["sentiment"].notna().any():
                counts = feedback["sentiment"].value_counts()
                total = counts.sum()
                c1, c2, c3 = st.columns(3)
                c1.metric("Positive", f"{round(100 * counts.get('Positive', 0) / total)}%")
                c2.metric("Neutral", f"{round(100 * counts.get('Neutral', 0) / total)}%")
                c3.metric("Negative", f"{round(100 * counts.get('Negative', 0) / total)}%")
            else:
                st.caption("No classified feedback yet.")
